version: "3.8"

services:
  monitoringdb:
    image: mysql
    container_name: db-monitoring
    restart: on-failure
    ports:
      - "3309:3306"
    environment:
      MYSQL_DATABASE: monitoringdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: admin
    networks:
      - ems-network

  monitoring-app:
    hostname: monitoring-communication
    restart: on-failure
    depends_on:
      - monitoringdb
    image: monitoring-communication-app
    container_name: monitoring-communication-container
    build: .
    ports:
      - "8002:8082"
    environment:
      - DB_IP=monitoringdb
    networks:
      - ems-network

networks:
  ems-network:
    external: true